### ISSUE TITLE
Project templates

### ISSUE THREAD

**Issue by y9vad9** [codee-team/codee-app#26]

**Comment by y9vad9** [comment]
Plugins should be able to create templates (for easier use of language/assembly plugins).
I propose to split this logic into the `ProjectsManager`.  The templates themselves will be categorized (and will be extensible from the outside in a similar form as in the API). Something like that:

### Plugin-supplier
We create class that implements `ProjectsCategory`:
```kotlin
public class PluginSupplierCategory : ProjectsCategory {
    public override val templates: MutableList<ProjectTemplate> = mutableListOf() // as for now, there is mutable list, but it is bad practise, so I need to think how to do it better.
}
```
`ProjectTemplate` there is just a class that contains some info (localized name, description, fields (text inputs, checkbox, etc). 
Somewhere in main script we register this category:
```kotlin
// Plugin is the receiver here
projectsManager.register<PluginSupplierCategory>(instance)
```

### Plugin-consumer
In `plugin-consumer` we just take it in the same way as it was in `PluginsApiManager`:
```kotlin
projectsManager.firstWithType<PluginSupplierCategory>().templates.add(...)
```
It will have same with `PluginsApiManager` compatibility settings.
#### ProjectTemplate
`ProjectTemplate` will have next structure:
- name: `LocalizedString`
- description: `LocalizedString`
- fields: `List<Field>`

Where `Field` is `sealed` interface that have different types of 'fields' (TextInput, Switch, etc):
- `Field`
  - `TextInput`:
    - `SimpleTextInput`: simple text input
    - `NumberInput`: text input with only number allowed mode.
  - `Switch`: simple on/off switch.
  - `Picker`:
    - `FolderPicker`
    - `FilePicker`

**Comment by y9san9** [comment]
Good job, but ...Manager is [AntiPattern ](https://stackoverflow.com/questions/1866794/naming-classes-how-to-avoid-calling-everything-a-whatevermanager).  You may choose for example `ProjectsContainer` or something else.
